server:
  port: 8085

#logging:
#  level:
#    org:
#      springframework: DEBUG

spring:
  cloud:
    config:
      enabled: false
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/