server:
  port: 8084

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sumitmaji/spring-app-prop-repo
          searchPaths: demo-resource-server
          cloneOnStart: true

####
#Classpath and file-based solution
####

#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#             searchLocations: classpath:config/,classpath:config/licensingservice
